apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: infra
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.1
    helm:
      values: |
        controller:
          replicaCount: 2
          service:
            type: LoadBalancer
            loadBalancerIP: PLACEHOLDER_INGRESS_IP
          config:
            use-forwarded-headers: "true"
            compute-full-forwarded-for: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
